version: '3.8'

services:
  savant-site-dev:
    build:
      context: .
      target: build
    container_name: savant-docs-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true 